Explicitly require commands
shelljs/shelljs pull request #1119
Opened 2023-03-10 21:26 UTC by Everspace

Currently anything that includes shelljs in it's chain cannot be bundled into a singular file due to the dynamic require. By explicitly requiring everything in src, this allows singular bundles through things like esbuild.

2024-05-12 13:49 UTC, TimothyJones commented
I'd love to see this merged - is there a reason not to?

2024-06-05 07:50 UTC, 7PH commented
I suggested another solution to this issue [in here](https://github.com/shelljs/shelljs/issues/1160), but I've only tested it with `esbuild`, it would be interesting to know if it also fixes the other bundlers

2024-10-29 15:42 UTC, Everspace commented
It would apply to every bundler @7PH

2024-10-29 15:58 UTC, 7PH commented
Later, I've tested [more bundlers](https://github.com/shelljs/shelljs/pull/1161#issuecomment-2170539764) and some already work, some don't with this project's `require`. But [my PR](https://github.com/shelljs/shelljs/pull/1161) isn't getting a lot of attention by the owner of `shelljs`.

2024-12-02 10:28 UTC, AlexanderLill commented
Dear maintainers @nfischer @freitagbr, please consider merging this minor change to make shelljs compatible with esbuild and other bundlers (see previous comments and many of the open issues, e.g. #1160 #1172 etc).

2025-02-20 07:19 UTC, nfischer commented on shell.js
> +// require('./src/exec-child'); excluded since it is for commandline only
Can we remove this line? This is just a code comment so it doesn't do anything in regular node. Is this commented-out code necessary in order to trick the bundler?

2025-02-20 09:13 UTC, Everspace commented
No, I thought it was nice for the sake of completeness of all the files in
./src, but I can remove it.

On Wed, Feb 19, 2025, 11:20 p.m. Nate Fischer ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In shell.js
> <https://github.com/shelljs/shelljs/pull/1119#discussion_r1962981643>:
>
> > @@ -21,9 +21,40 @@ var common = require('./src/common');
>  ***@***.***
>
>  // Load all default commands
> -require('./commands').forEach(function (command) {
> -  require('./src/' + command);
> -});
> +require('./src/cat');
> +require('./src/cd');
> +require('./src/chmod');
> +require('./src/cmd');
> +require('./src/common');
> +require('./src/cp');
> +require('./src/dirs');
> +require('./src/echo');
> +require('./src/error');
> +require('./src/errorCode');
> +// require('./src/exec-child'); excluded since it is for commandline only
>
> Can we remove this line? This is just a code comment so it doesn't do
> anything in regular node. Is this commented-out code necessary in order to
> trick the bundler?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shelljs/shelljs/pull/1119#pullrequestreview-2628908237>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZV3OZALOID7MN2EAPNODT2QV62LAVCNFSM6AAAAAAVW64P42VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDMMRYHEYDQMRTG4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2025-02-20 09:54 UTC, nfischer requested changes
Can you please do the following:

* Rebase on top of latest master branch, including PR #1187
* Remove the `commands.js` file
* Edit `package.json` to remove the reference to `commands.js`
* Please confirm if this PR will fix either #1160 and #1172

2025-02-20 09:54 UTC, nfischer commented on shell.js
> +// require('./src/exec-child'); excluded since it is for commandline only
I think you should change this to just actually `require()` the exec-child.js file. If you rebase on the lastest master branch, then I have changed this to be a NOOP. I think requiring is necessary to trick the bundler into realizing this file is necessary.

2025-03-08 22:33 UTC, nfischer approved these changes

2025-03-08 22:33 UTC, nfischer commented
I'm going to approve now and land this. I'll send the necessary patches for followup fixes.

Thanks for your contribution!

2025-03-08 22:33 UTC, merged

2025-03-08 23:13 UTC, Everspace commented
Ack I am so sorry, I've been busy. Thank you very much for your help and getting this merged in.