Fix Windows test errors in src/ls.js and test/cp.js.
shelljs/shelljs pull request #1165
Opened 2024-06-19 03:22 UTC by kmashint

These are fixes for Windows in the switch-fast-blob branch as mentioned in this pull-request.
https://github.com/shelljs/shelljs/pull/1153

2024-06-19 18:41 UTC, nfischer approved these changes

2024-06-21 22:22 UTC, nfischer commented
@kmashint can you please rebase this PR on top of the `master` branch instead? I realized this change is missing some critical commits that I landed recently on `master`. I'm hoping that your fixes are backward compatible with both `glob` and `fast-glob` so this should be relatively easy to land.

2024-06-21 23:19 UTC, kmashint commented
@nfischer Will rebase on master tonight.

2024-06-21 23:49 UTC, kmashint commented
I merged master into this pull-request branch, and hoping I cut it the right way, removing references to glob in favour of fast-glob.

2024-06-22 01:16 UTC, nfischer requested changes

2024-06-22 01:16 UTC, nfischer commented on src/common.js
> -function globOptions() {
I think this was reverted when it should not have been. I think what happened is that you probably have an out-of-date copy of the `master` branch. Can you please sync this against the main repo's master branch? I think you can do this with something like:

```
git checkout master
git remote add upstream https://github.com/shelljs/shelljs.git
git fetch upstream
git rebase upstream/master
git checkout switch-fast-glob
git rebase master
git push origin switch-fast-glob --force-with-lease
```

2024-06-22 01:19 UTC, nfischer commented on package.json
> +    "fast-glob": "^3.3.2",
Also, I would like to exclude this part from this PR. My change will take care of switching over to `fast-glob`. I'd like to merge your change before mine though to make sure it is backward-compatible with "plain" `glob. Then I'll rebase my change on top of yours to test it with `fast-glob`.

It's also fine if you want to test this with `fast-glob` locally in your checkout. We should just remove this part before merging this on the `master` branch.

2024-06-22 22:49 UTC, nfischer commented
Closing this one in favor of #1166.

2024-06-22 22:49 UTC, closed without merging